<a href="https://colab.research.google.com/github/PeddapalliAbhinav/2403A51L38_52/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [23]:
marks = 50 + (100 - 50) * np.random.rand(5, 4)

In [25]:
marks = marks.astype(int)

In [26]:
print(marks)

[[95 77 77 65]
 [89 65 53 78]
 [96 57 70 62]
 [60 53 75 71]
 [83 79 69 71]]


In [27]:
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [78.5  71.25 71.25 64.75 75.5 ]
Average marks per subject: [84.6 66.2 68.8 69.4]
Highest marks in each subject: [96 79 77 78]
Lowest marks in each subject: [60 53 53 62]
